<div style="text-align: center;">

<h1 style="color: #E50914; font-size: 40px;">
NETFLIX MOVIES AND TV SHOWS
</h1>

<p style="font-size: 18px; color: #555;text-align: center;">
Data Cleaning Project
</p>

</div>

<div style="text-align: center;">

<img src="netflix.jpg" 
     style="width: 100%; max-width: 1200px; border-radius: 10px;">

</div>

<div style="
    background-color: white;
    color: black;
    padding: 15px;
    text-align: center;
    font-family: Georgia, serif;
">

<h1 style="
    color: black;
    font-size: 32px;
    margin: 0;
">
INTRODUCTION
</h1>

</div>
<p style="
    font-family: Arial, sans-serif;
    font-size: 17px;
    color: black;
    line-height: 1.7;
    text-align: justify;
">


Data cleaning is the process of identifying and correcting errors, missing values, duplicates, and inconsistencies in a dataset. This project focuses on cleaning the **Netflix Movies and TV Shows dataset** using **Python Pandas in Jupyter Notebook**. The cleaned data can be used for further analysis.


</p>

<div style="
    background-color: white;
    color: black;
    padding: 15px;
    text-align: center;
    font-family: Georgia, serif;
">

<h1 style="
    color: black;
    font-size: 32px;
    margin: 0;
">
Abstract
</h1>

</div>
<p style="
    font-family: Arial, sans-serif;
    font-size: 17px;
    color: black;
    line-height: 1.7;
    text-align: justify;
">
    
This project involves cleaning the Netflix Movies and TV Shows dataset using Pandas. The dataset contains information about movies and TV shows available on Netflix. The cleaning process includes handling missing values, checking duplicates, correcting data types, and standardizing data to make it suitable for further analysis.

</p>

<div style="
    background-color: white;
    color: black;
    padding: 15px;
    text-align: center;
    font-family: Georgia, serif;
">

<h1 style="
    color: black;
    font-size: 32px;
    margin: 0;
">
About The Dataset
</h1>

</div>
<p style="
    font-family: Arial, sans-serif;
    font-size: 17px;
    color: black;
    line-height: 1.7;
    text-align: justify;
">
    

The **Netflix Movies and TV Shows dataset** contains information about movies and TV shows available on Netflix. It has **8,807 records and 12 columns**, including title, type, director, cast, country, release year, rating, duration, genre, and description. The dataset is useful for understanding and analyzing Netflix content.

</p>

<div style="
    background-color: white;
    color: black;
    padding: 15px;
    text-align: center;
    font-family: Georgia, serif;
">

<h1 style="
    color: black;
    font-size: 32px;
    margin: 0;
">
Column Description
</h1>

<table border="1" style="border-collapse: collapse;">
<tr>
    <th>Column</th>
    <th>Description</th>
</tr>
<tr><td>show_id</td><td>Unique ID of the title</td></tr>
<tr><td>type</td><td>Movie or TV Show</td></tr>
<tr><td>title</td><td>Name of the title</td></tr>
<tr><td>director</td><td>Director of the title</td></tr>
<tr><td>cast</td><td>Actors and cast members</td></tr>
<tr><td>country</td><td>Country of production</td></tr>
<tr><td>date_added</td><td>Date added to Netflix</td></tr>
<tr><td>release_year</td><td>Original release year</td></tr>
<tr><td>rating</td><td>Content rating</td></tr>
<tr><td>duration</td><td>Movie duration or number of seasons</td></tr>
<tr><td>listed_in</td><td>Genre or category</td></tr>
<tr><td>description</td><td>Short description of the title</td></tr>
</table>

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("netflix_titles.csv")

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [5]:
df.shape

(8807, 12)

In [6]:
df.size

105684

In [7]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

<div style="
    background-color: white;
    color: black;
    padding: 15px;
    text-align: center;
    font-family: Georgia, serif;
">

<h1 style="
    color: black;
    font-size: 32px;
    margin: 0;
">
DATA CLEANING
</h1>

In [8]:
# missing values in dataset
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

# <CENTER>Fill Missing Values

In [9]:
df["director"].fillna("Not Available",inplace=True)

In [10]:
df["cast"].fillna(df["cast"].mode()[0], inplace=True)

In [11]:
df["country"].fillna(df["country"].mode()[0], inplace=True)

In [12]:
df["date_added"].fillna(df["date_added"].mode()[0], inplace=True)

In [13]:
df["rating"].fillna(df["rating"].mode()[0], inplace=True)

In [14]:
df["duration"].fillna(df["duration"].mode()[0], inplace=True)

In [15]:
#recheking if any null values exist
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [16]:
#check for count of duplicate values
df.duplicated().sum()

np.int64(0)

In [17]:
#save modified dataset
df.to_csv("new_netflix_titles.csv",index=False)

<div style="
    background-color: white;
    color: black;
    padding: 15px;
    text-align: center;
    font-family: Georgia, serif;
">

<h1 style="
    color: black;
    font-size: 32px;
    margin: 0;
">
CONCLUSION
</h1>

</div>
<p style="
    font-family: Arial, sans-serif;
    font-size: 17px;
    color: black;
    line-height: 1.7;
    text-align: justify;
">

The Netflix Movies and TV Shows dataset was successfully cleaned using Python and Pandas. Missing values in columns such as director, cast, country, date added, rating, and duration were handled appropriately. The dataset was also checked for duplicate values and inconsistencies. After the cleaning process, the dataset contains no missing or duplicate values. Thus, the dataset is now clean, consistent, and ready for further use.
</p>