In [1]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [4]:
df.shape

(1338, 7)

In [5]:
df.size

9366

## Checking Unique Values

In [8]:
for col in df.columns:

   if df[col].nunique() <= 10:
     print(f"\nColumn: {col}")
     print(df[col].unique())

Column: sex
['female' 'male']

Column: children
[0 1 3 2 5 4]

Column: smoker
['yes' 'no']

Column: region
['southwest' 'southeast' 'northwest' 'northeast']

## Data Set Informations

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [7]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

## Check Missing Values

In [9]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

## Check Duplicates

In [10]:
print(df.duplicated().sum())

1

## Remove Duplicates

In [12]:
df.drop_duplicates(inplace=True)

## Recheck Duplicates

In [13]:
print(df.duplicated().sum())

0

## Feature Selection

In [14]:
df.drop(columns=["region"], inplace=True)
df.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

## Outlier Detection

In [15]:
columns = df.select_dtypes(include = "number").columns

# Calculate Z-score
z_scores = np.abs(zscore(df[columns]))

# Identify outliers
outlier_counts = (z_scores > 3).sum(axis=0)

# Print column name and number of outliers
for i in range(len(columns)):
 print(columns[i], ":", outlier_counts[i], "outliers")

age : 0 outliers
bmi : 4 outliers
children : 18 outliers
charges : 7 outliers

## The Actual Outlier Values

In [16]:
for column in columns:

 z = np.abs(zscore(df[column]))

 print("\n", column)
 print(df[column][z > 3])

 age
Series([], Name: age, dtype: int64)

 bmi
116     49.06
847     50.38
1047    52.58
1317    53.13
Name: bmi, dtype: float64

 children
32      5
71      5
166     5
413     5
425     5
438     5
568     5
640     5
877     5
932     5
937     5
969     5
984     5
1085    5
1116    5
1130    5
1245    5
1272    5
Name: children, dtype: int64

 charges
34      51194.55914
543     63770.42801
577     58571.07448
819     55135.40209
1146    52590.82939
1230    60021.39897
1300    62592.87309
Name: charges, dtype: float64

## Outlier Handling

In [19]:
outlier_cols = ["bmi","children","charges"]

In [20]:
df_clean = df.copy()
for column in outlier_cols:

 z = np.abs(zscore(df_clean[column]))

 median = df_clean[column].median()

 df_clean.loc[z > 3, column] = median

In [21]:
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

Original shape: (1337, 6)
Cleaned shape: (1337, 6)

## Outlier Removal

In [22]:
df_clean = df.copy()
for column in outlier_cols:
 z = np.abs(zscore(df_clean[column]))
 df_clean = df_clean[z <= 3]
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

Original shape: (1337, 6)
Cleaned shape: (1308, 6)