## <CENTER> Outlier Detection and Handling-Z_score Method

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [4]:
df.shape

(891, 12)

In [5]:
df.size

10692

## Checking unique values

In [8]:
for col in df.columns:

   if df[col].nunique() <= 10:
     print(f"\nColumn: {col}")
     print(df[col].unique())

Column: Survived
[0 1]

Column: Pclass
[3 1 2]

Column: Sex
['male' 'female']

Column: SibSp
[1 0 3 4 2 5 8]

Column: Parch
[0 1 2 5 3 4 6]

Column: Embarked
['S' 'C' 'Q' nan]

## Dataset Informations

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [10]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Check missing values

In [11]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## Handle Missing Values

In [12]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)
df["Cabin"].fillna("Unknown", inplace=True)

df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## Remove duplicates

In [13]:
print(df.duplicated().sum())

0

## Feature Selection

In [14]:
df.drop(columns=["PassengerId","Name","Ticket"], inplace=True)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare    Cabin Embarked
0         0       3    male  22.0      1      0   7.2500  Unknown        S
1         1       1  female  38.0      1      0  71.2833      C85        C
2         1       3  female  26.0      0      0   7.9250  Unknown        S
3         1       1  female  35.0      1      0  53.1000     C123        S
4         0       3    male  35.0      0      0   8.0500  Unknown        S

## Outlier Detection

In [16]:
columns = df.select_dtypes(include = "number").columns

# Calculate Z-score
z_scores = np.abs(zscore(df[columns]))

# Identify outliers
outlier_counts = (z_scores > 3).sum(axis=0)

# Print column name and number of outliers
for i in range(len(columns)):
 print(columns[i], ":", outlier_counts[i], "outliers")

Survived : 0 outliers
Pclass : 0 outliers
Age : 7 outliers
SibSp : 30 outliers
Parch : 15 outliers
Fare : 20 outliers

## The actual outlier values

In [17]:
for column in columns:

 z = np.abs(zscore(df[column]))

 print("\n", column)
 print(df[column][z > 3])

 Survived
Series([], Name: Survived, dtype: int64)

 Pclass
Series([], Name: Pclass, dtype: int64)

 Age
96     71.0
116    70.5
493    71.0
630    80.0
672    70.0
745    70.0
851    74.0
Name: Age, dtype: float64

 SibSp
16     4
50     4
59     5
68     4
71     5
119    4
159    8
164    4
171    4
180    8
182    4
201    8
233    4
261    4
266    4
278    4
324    8
386    5
480    5
541    4
542    4
683    5
686    4
787    4
792    8
813    4
824    4
846    8
850    4
863    8
Name: SibSp, dtype: int64

 Parch
13     5
25     5
86     3
167    4
360    4
437    3
438    4
567    4
610    5
638    5
678    6
736    3
774    3
858    3
885    5
Name: Parch, dtype: int64

 Fare
27     263.0000
88     263.0000
118    247.5208
258    512.3292
299    247.5208
311    262.3750
341    263.0000
377    211.5000
380    227.5250
438    263.0000
527    221.7792
557    227.5250
679    512.3292
689    211.3375
700    227.5250
716    227.5250
730    211.3375
737    512.3292
742    262.3750
779    211.3375
Name: Fare, dtype: float64

## Outlier Handling

In [20]:
outlier_cols = ["Age","Fare"]

In [22]:
df_clean = df.copy()
for column in outlier_cols:

 z = np.abs(zscore(df_clean[column]))

 median = df_clean[column].median()

 df_clean.loc[z > 3, column] = median

In [23]:
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

Original shape: (891, 9)
Cleaned shape: (891, 9)

## Outlier Removal

In [24]:
df_clean = df.copy()
for column in outlier_cols:
 z = np.abs(zscore(df_clean[column]))
 df_clean = df_clean[z <= 3]
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

Original shape: (891, 9)
Cleaned shape: (864, 9)